spring.application.name=market-dashboard

# Alpha Vantage API Key
alphavantage.api.key= ${ALPHA_VANTAGE_API_KEY}
alphavantage.base.url=https://www.alphavantage.co/query

# CoinGecko - no key needed
coingecko.base.url=https://api.coingecko.com/api/v3

# Cache TTL in seconds (60s for prices, 300s for market overviews)
cache.crypto.ttl=60
cache.stocks.ttl=60

# CORS - allow local React dev server
cors.allowed.origins=http://localhost:5173

# Logging
logging.level.com.marketdashboard=DEBUG

#Open API docs
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
